### ISSUE TITLE
nuget package?

### ISSUE THREAD

**Issue by bmabey** [BlueMountainCapital/riemann-csharp#2]
Will you be pushing this driver to the public NuGet feed or would you accept a PR that did the packaging?

**Comment by chillitom** [comment]
:+1:

**Comment by AnthonySteele** [comment]
Agreed that this is important. Project owners should get a nuget account and an upload key and do this.
I have a powershell script that makes uploading a new version a one-command operation.  (see https://github.com/AnthonySteele/MvcRouteTester/tree/master/buildpackage )
I can adapt this, if powershell is the way that you want to go...

**Comment by garethbudden** [comment]
:+1:

**Comment by AnthonySteele** [comment]
What is the plan for nuget on this project? Has a decision been made to not make a nuget package?

**Comment by bmabey** [comment]
@carlyeks, WDYT?  If someone sends you a PR for NuGet will you merge it and push packages?

(BTW, I probably won't be doing a PR anytime soon since we've gone a different route with monitoring for c#... for now.)

**Comment by carlyeks** [comment]
Yes, I will get this package included in NuGet. I'm hoping to get to it today.

**Comment by AnthonySteele** [comment]
Thanks!

**Comment by carlyeks** [comment]
Pushed out: https://www.nuget.org/packages/riemann-csharp/

Thanks @AnthonySteele for pointing me to your example; definitely made it easier.
